#!/usr/bin/env python3
"""
make-space.py — scaffold (and optionally deploy) a HuggingFace Gradio Space that
wraps a single-image-processing Python tool. Framework-level + reusable: point it
at any stack's tool and it predictively builds the UI.

Predictive model
----------------
The target tool exposes a function with the convention:
    fn(input_path: str, output_path: str, *tunables)
make-space introspects that signature (names + defaults) to auto-generate Gradio
controls. An optional sidecar manifest `<tool>.space.json` overrides labels,
slider ranges, docs, requirements, and metadata.

Manifest (all keys optional):
{
  "title": "...", "emoji": "🎨", "colorFrom": "pink", "colorTo": "indigo",
  "fn": "grade", "description": "markdown...", "license": "mit",
  "requirements": ["numpy","pillow","opencv-python-headless"],
  "params": [
    {"name":"strength","type":"slider","min":0,"max":1,"step":0.05,"default":0.85,"label":"WB strength","info":"..."},
    {"name":"denoise","type":"checkbox","default":true,"label":"Denoise"}
  ]
}

Usage:
  make-space.py --tool PATH/to/tool.py --space-id USER/NAME [--fn grade]
      [--manifest PATH] [--out DIR] [--private|--public]
      [--hardware cpu-basic] [--title T] [--emoji E] [--deploy]

Exit: 0 ok, 2 usage error, 1 failure.
"""
import argparse, importlib.util, inspect, json, os, shutil, sys, textwrap


def log(m): print(f"[make-space] {m}", flush=True)


def load_manifest(tool_path, explicit):
    cand = explicit or os.path.splitext(tool_path)[0] + ".space.json"
    if cand and os.path.isfile(cand):
        with open(cand) as f:
            log(f"manifest: {cand}")
            return json.load(f)
    log("manifest: none (introspecting signature)")
    return {}


def import_fn(tool_path, fn_name):
    spec = importlib.util.spec_from_file_location("tool_mod", tool_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, fn_name):
        sys.exit(f"[make-space] ERROR: {tool_path} has no function '{fn_name}'")
    return getattr(mod, fn_name)


def params_from_signature(fn):
    """Everything after the first two positional args (input, output) is a tunable."""
    sig = inspect.signature(fn)
    names = list(sig.parameters)[2:]
    out = []
    for n in names:
        d = sig.parameters[n].default
        if isinstance(d, bool):
            out.append({"name": n, "type": "checkbox", "default": d, "label": n})
        elif isinstance(d, (int, float)):
            hi = 1.0 if 0 <= d <= 1 else max(6.0, d * 2)
            out.append({"name": n, "type": "slider", "min": 0.0, "max": hi,
                        "step": 0.05 if hi <= 1.5 else 0.5, "default": float(d), "label": n})
        else:
            out.append({"name": n, "type": "text", "default": "" if d is inspect._empty else d, "label": n})
    return out


def gen_app_py(tool_module, fn_name, params, manifest):
    title = manifest.get("title", fn_name)
    desc = manifest.get("description", "Image processing tool.")
    # build component constructors + call args
    comp_lines, call_args = [], []
    for p in params:
        nm, lbl = p["name"], p.get("label", p["name"])
        info = json.dumps(p.get("info", ""))
        if p["type"] == "slider":
            comp_lines.append(
                f'    gr.Slider({p.get("min",0)}, {p.get("max",1)}, value={p.get("default",0)}, '
                f'step={p.get("step",0.05)}, label={json.dumps(lbl)}, info={info}),')
        elif p["type"] == "checkbox":
            comp_lines.append(
                f'    gr.Checkbox(value={bool(p.get("default", False))}, label={json.dumps(lbl)}, info={info}),')
        else:
            comp_lines.append(
                f'    gr.Textbox(value={json.dumps(p.get("default",""))}, label={json.dumps(lbl)}),')
        call_args.append(nm)
    comps = "\n".join(comp_lines)
    coerce = "\n".join(
        f'{p["name"]} = (1 if {p["name"]} else 0)'
        for p in params if p["type"] == "checkbox")
    callsig = ", ".join(call_args)
    return f'''#!/usr/bin/env python3
"""Auto-generated by comfyui-provisioner/scripts/make-space.py — do not hand-edit;
re-run the scaffolder to regenerate."""
import os, tempfile, gradio as gr
from {tool_module} import {fn_name} as _run

DESCRIPTION = {json.dumps(desc)}

def process(image_path, {callsig}):
    if not image_path:
        raise gr.Error("Upload an image first.")
{textwrap.indent(coerce, "    ") if coerce else "    pass"}
    out = os.path.join(tempfile.mkdtemp(), "out.png")
    _run(image_path, out, {callsig})
    return out

with gr.Blocks(title={json.dumps(title)}) as demo:
    gr.Markdown(f"# {title}\\n\\n{{DESCRIPTION}}")
    with gr.Row():
        with gr.Column():
            inp = gr.Image(type="filepath", label="Input image")
            controls = [
{textwrap.indent(comps, "        ")}
            ]
            btn = gr.Button("Run", variant="primary")
        with gr.Column():
            outp = gr.Image(type="filepath", label="Result", format="png")
    btn.click(process, inputs=[inp, *controls], outputs=outp)
    inp.upload(process, inputs=[inp, *controls], outputs=outp)

if __name__ == "__main__":
    demo.launch()
'''


def gen_readme(space_id, manifest, params):
    name = space_id.split("/")[-1]
    title = manifest.get("title", name)
    emoji = manifest.get("emoji", "🎨")
    cf = manifest.get("colorFrom", "pink"); ct = manifest.get("colorTo", "indigo")
    lic = manifest.get("license", "mit")
    sdkver = manifest.get("sdk_version", "5.49.1")  # gradio 5.x: compatible with huggingface_hub 1.x
    # Pin Python 3.12: gradio 4.x depends on pydub -> audioop, removed from py3.13 stdlib
    # (HF's default base image). 3.12 keeps audioop available.
    pyver = manifest.get("python_version", "3.12")
    rows = "\n".join(f"| `{p['name']}` | {p.get('label','')} | "
                     f"{p.get('default','')} | {p.get('info','')} |" for p in params)
    body = manifest.get("description", "")
    return f'''---
title: {title}
emoji: {emoji}
colorFrom: {cf}
colorTo: {ct}
sdk: gradio
sdk_version: {sdkver}
python_version: "{pyver}"
app_file: app.py
pinned: false
license: {lic}
---

# {emoji} {title}

{body}

## Controls

| Parameter | Label | Default | Notes |
|---|---|---|---|
{rows}

## How it works

This Space wraps a standalone Python tool (no GPU required). The same tool runs
locally and in batch — this UI is just a thin Gradio front end generated by
[`comfyui-provisioner`](https://github.com/ismail-kattakath/comfyui-provisioner)
`scripts/make-space.py`. Re-run that scaffolder to regenerate the app.

_Auto-generated Space scaffold. Upload an image and adjust the controls._
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tool", required=True)
    ap.add_argument("--space-id", required=True, help="USER/NAME on HuggingFace")
    ap.add_argument("--fn", default=None)
    ap.add_argument("--manifest", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--private", action="store_true", default=True)
    ap.add_argument("--public", dest="private", action="store_false")
    ap.add_argument("--hardware", default="cpu-basic")
    ap.add_argument("--title", default=None)
    ap.add_argument("--emoji", default=None)
    ap.add_argument("--deploy", action="store_true")
    a = ap.parse_args()

    if not os.path.isfile(a.tool):
        sys.exit(f"[make-space] ERROR: tool not found: {a.tool}")
    manifest = load_manifest(a.tool, a.manifest)
    if a.title: manifest["title"] = a.title
    if a.emoji: manifest["emoji"] = a.emoji
    fn_name = a.fn or manifest.get("fn", "grade")
    fn = import_fn(a.tool, fn_name)
    params = manifest.get("params") or params_from_signature(fn)

    out = a.out or os.path.join(os.path.dirname(os.path.abspath(a.tool)),
                                "spaces", a.space_id.split("/")[-1])
    os.makedirs(out, exist_ok=True)
    tool_base = os.path.basename(a.tool)
    tool_module = os.path.splitext(tool_base)[0]
    shutil.copy2(a.tool, os.path.join(out, tool_base))

    with open(os.path.join(out, "app.py"), "w") as f:
        f.write(gen_app_py(tool_module, fn_name, params, manifest))
    reqs = ["gradio"] + manifest.get("requirements", ["numpy", "pillow", "opencv-python-headless"])
    with open(os.path.join(out, "requirements.txt"), "w") as f:
        f.write("\n".join(dict.fromkeys(reqs)) + "\n")
    with open(os.path.join(out, "README.md"), "w") as f:
        f.write(gen_readme(a.space_id, manifest, params))
    log(f"scaffolded -> {out}")
    log(f"  files: app.py, {tool_base}, requirements.txt, README.md")
    log(f"  params: {[p['name'] for p in params]}")

    if not a.deploy:
        log("scaffold only (no --deploy). Review the folder, then re-run with --deploy.")
        return

    tok = os.environ.get("HF_TOKEN")
    if not tok:
        sys.exit("[make-space] ERROR: HF_TOKEN not set; cannot deploy.")
    try:
        from huggingface_hub import HfApi
    except ImportError:
        sys.exit("[make-space] ERROR: pip install huggingface_hub to deploy.")
    api = HfApi(token=tok)
    log(f"creating space {a.space_id} (private={a.private}, sdk=gradio)")
    api.create_repo(repo_id=a.space_id, repo_type="space", space_sdk="gradio",
                    private=a.private, exist_ok=True)
    api.upload_folder(folder_path=out, repo_id=a.space_id, repo_type="space",
                      commit_message="Deploy via make-space.py")
    log(f"DEPLOYED: https://huggingface.co/spaces/{a.space_id}")


if __name__ == "__main__":
    main()
