#!/usr/bin/env bash
# scripts/refresh-workspace.sh
#
# Regenerate the multi-root VS Code workspace file and the devcontainer
# compose-siblings fragment based on whatever comfyui-stack-* siblings of
# this provisioner repo currently exist on disk.
#
# Both outputs are gitignored — they describe THIS machine's working set,
# not anything about the tool itself.
#
# Safe to call any time; idempotent; no network access.
#
# Anchors paths to this script's own location, not $PWD — so it works the
# same when run from a slash command, an initializeCommand hook, or by hand.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVISIONER_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PARENT_DIR="$(cd "$PROVISIONER_ROOT/.." && pwd)"
PROVISIONER_NAME="$(basename "$PROVISIONER_ROOT")"

WORKSPACE_FILE="$PROVISIONER_ROOT/comfyui-workspace.code-workspace"
COMPOSE_FILE="$PROVISIONER_ROOT/.devcontainer/docker-compose.siblings.yml"

shopt -s nullglob
SIBLINGS=()
for d in "$PARENT_DIR"/comfyui-stack-*; do
  [[ -d "$d" ]] || continue
  SIBLINGS+=("$(basename "$d")")
done
shopt -u nullglob

# Sort for deterministic output (diff-friendly across runs)
if [[ ${#SIBLINGS[@]} -gt 0 ]]; then
  IFS=$'\n' SIBLINGS=($(printf '%s\n' "${SIBLINGS[@]}" | sort))
  unset IFS
fi

# --- Workspace file (multi-root) ---
{
  printf '{\n'
  printf '  "folders": [\n'
  printf '    { "name": "%s", "path": "." }' "$PROVISIONER_NAME"
  for s in "${SIBLINGS[@]}"; do
    printf ',\n    { "name": "%s", "path": "../%s" }' "$s" "$s"
  done
  printf '\n  ],\n'
  printf '  "settings": {\n'
  printf '    "files.exclude": { "**/.DS_Store": true }\n'
  printf '  }\n'
  printf '}\n'
} > "$WORKSPACE_FILE"

# --- Devcontainer compose-siblings fragment ---
# Extends docker-compose.yml's `devcontainer` service with one bind mount per
# sibling. The base docker-compose.yml already mounts provisioner at
# /workspaces/<provisioner-name>; this adds /workspaces/<sibling> for each.
{
  printf '# Auto-generated by scripts/refresh-workspace.sh. Do not edit by hand.\n'
  printf '# Regenerated by /ensure-stack and the devcontainer initializeCommand hook.\n'
  printf '# Listed siblings: %d\n' "${#SIBLINGS[@]}"
  printf 'services:\n'
  printf '  devcontainer:\n'
  if [[ ${#SIBLINGS[@]} -eq 0 ]]; then
    printf '    volumes: []  # no comfyui-stack-* siblings present\n'
  else
    printf '    volumes:\n'
    for s in "${SIBLINGS[@]}"; do
      # Path is relative to the .devcontainer/ directory (where compose runs from)
      printf '      - ../../%s:/workspaces/%s:cached\n' "$s" "$s"
    done
  fi
} > "$COMPOSE_FILE"

echo "[refresh-workspace] $WORKSPACE_FILE (${#SIBLINGS[@]} sibling(s))" >&2
echo "[refresh-workspace] $COMPOSE_FILE" >&2
